#!/usr/bin/env python3
import rospy
from geometry_msgs.msg import TransformStamped
from robp_msgs.msg import Encoders
from nav_msgs.msg import Path
from tf.transformations import euler_from_quaternion
from geometry_msgs.msg import PoseStamped, Point, Twist, TransformStamped


class get_goal():

    def __init__(self):

        self.publisher_goal = rospy.Publisher('move_base_simple/goal', PoseStamped, queue_size=10)

        self.goal = Point()
        self.goal_pos_x = 1
        self.goal_pos_y = 1

        self.run()

    
    def run(self):

        while not rospy.is_shutdown():

            self.goal_pos_x = self.goal_pose_x
            self.goal_pos_y = self.goal_pose_y

            self.publisher_goal.publish(self.goal)


if __name__ == "__main__":
    try:
        rospy.init_node("get_goal") 
        get_goal()      
        rospy.spin()
    except rospy.ROSInterruptException:
        pass