// Generated by gencpp from file robp_msgs/DutyCycles.msg
// DO NOT EDIT!


#ifndef ROBP_MSGS_MESSAGE_DUTYCYCLES_H
#define ROBP_MSGS_MESSAGE_DUTYCYCLES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace robp_msgs
{
template <class ContainerAllocator>
struct DutyCycles_
{
  typedef DutyCycles_<ContainerAllocator> Type;

  DutyCycles_()
    : header()
    , duty_cycle_left(0.0)
    , duty_cycle_right(0.0)  {
    }
  DutyCycles_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , duty_cycle_left(0.0)
    , duty_cycle_right(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _duty_cycle_left_type;
  _duty_cycle_left_type duty_cycle_left;

   typedef double _duty_cycle_right_type;
  _duty_cycle_right_type duty_cycle_right;





  typedef boost::shared_ptr< ::robp_msgs::DutyCycles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robp_msgs::DutyCycles_<ContainerAllocator> const> ConstPtr;

}; // struct DutyCycles_

typedef ::robp_msgs::DutyCycles_<std::allocator<void> > DutyCycles;

typedef boost::shared_ptr< ::robp_msgs::DutyCycles > DutyCyclesPtr;
typedef boost::shared_ptr< ::robp_msgs::DutyCycles const> DutyCyclesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robp_msgs::DutyCycles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robp_msgs::DutyCycles_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robp_msgs::DutyCycles_<ContainerAllocator1> & lhs, const ::robp_msgs::DutyCycles_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.duty_cycle_left == rhs.duty_cycle_left &&
    lhs.duty_cycle_right == rhs.duty_cycle_right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robp_msgs::DutyCycles_<ContainerAllocator1> & lhs, const ::robp_msgs::DutyCycles_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robp_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robp_msgs::DutyCycles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robp_msgs::DutyCycles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robp_msgs::DutyCycles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robp_msgs::DutyCycles_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robp_msgs::DutyCycles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robp_msgs::DutyCycles_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robp_msgs::DutyCycles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "543f5f160fe8968f328a223a093313c7";
  }

  static const char* value(const ::robp_msgs::DutyCycles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x543f5f160fe8968fULL;
  static const uint64_t static_value2 = 0x328a223a093313c7ULL;
};

template<class ContainerAllocator>
struct DataType< ::robp_msgs::DutyCycles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robp_msgs/DutyCycles";
  }

  static const char* value(const ::robp_msgs::DutyCycles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robp_msgs::DutyCycles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"# Value should be in [-1, 1], negative is backwards, positive forwards\n"
"float64 duty_cycle_left\n"
"float64 duty_cycle_right\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::robp_msgs::DutyCycles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robp_msgs::DutyCycles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.duty_cycle_left);
      stream.next(m.duty_cycle_right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DutyCycles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robp_msgs::DutyCycles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robp_msgs::DutyCycles_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "duty_cycle_left: ";
    Printer<double>::stream(s, indent + "  ", v.duty_cycle_left);
    s << indent << "duty_cycle_right: ";
    Printer<double>::stream(s, indent + "  ", v.duty_cycle_right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBP_MSGS_MESSAGE_DUTYCYCLES_H
